# Generated by Django 4.1.6 on 2023-02-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIF', 'ACTIF'), ('INACTIF', 'INACTIF')], max_length=200, null=True),
        ),
    ]
