# Generated by Django 4.1.6 on 2023-02-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0002_produit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
