# Generated by Django 4.1.6 on 2023-02-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_produit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='date',
            new_name='date_creation',
        ),
    ]
