# Generated by Django 4.1.6 on 2023-02-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0005_typeemballage'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeemballage',
            name='code_barre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
