# Generated by Django 4.1.6 on 2023-02-10 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stock', '0006_typeemballage_code_barre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('adresse_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('date_creation', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Approvision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantité_approvision', models.FloatField(blank=True, max_length=200, null=True)),
                ('date_approvision', models.DateField(auto_now_add=True, null=True)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.fournisseur')),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_emballage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.typeemballage')),
            ],
        ),
    ]
