# Generated by Django 4.1.6 on 2023-02-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0007_fournisseur_approvision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvision',
            old_name='quantité_approvision',
            new_name='quantite_approvision',
        ),
        migrations.AddField(
            model_name='approvision',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
