# Generated by Django 4.1.6 on 2023-02-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0008_rename_quantité_approvision_approvision_quantite_approvision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIF', 'ACTIF'), ('INACTIF', 'INACTIF')], max_length=200, null=True),
        ),
    ]
