# Generated by Django 4.1.6 on 2023-02-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0009_fournisseur_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvision',
            name='date_renseigner',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='typeemballage',
            name='quantite_stock',
            field=models.FloatField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
