# Generated by Django 4.1.6 on 2023-02-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0010_approvision_date_renseigner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeemballage',
            name='libelle',
            field=models.CharField(blank=True, choices=[('DETAIL', 'DETAIL'), ('CARTON', 'CARTON'), ('PACK', 'PACK')], max_length=200, null=True),
        ),
    ]
