# Generated by Django 4.1.6 on 2023-02-14 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stock', '0014_alter_typeemballage_quantite_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_client', models.CharField(blank=True, max_length=200, null=True)),
                ('date_facture', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_vente', models.FloatField(blank=True, max_length=200, null=True)),
                ('date_vente', models.DateField(auto_now_add=True, null=True)),
                ('save_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type_emballage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.typeemballage')),
            ],
        ),
    ]
