# Generated by Django 4.1.6 on 2023-02-14 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0015_facture_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.facture'),
        ),
    ]
