# Generated by Django 4.1.6 on 2023-02-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0016_vente_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='total_unitaire',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
