# Generated by Django 4.1.6 on 2023-03-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0023_approvision_facture_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvision',
            name='prix_unitaire',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
