# Generated by Django 4.1.6 on 2023-03-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0024_approvision_prix_unitaire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturefournisseur',
            old_name='date_facture',
            new_name='date_enregistrement',
        ),
        migrations.RemoveField(
            model_name='approvision',
            name='reference',
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='date_facturation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='montant_facture',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Versement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avance', models.FloatField(blank=True, max_length=200, null=True)),
                ('reste_a_payer', models.FloatField(blank=True, max_length=200, null=True)),
                ('date_versement', models.DateField(blank=True, null=True)),
                ('facture_fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.facturefournisseur')),
            ],
        ),
    ]
