# Generated by Django 4.1.6 on 2023-03-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0025_rename_date_facture_facturefournisseur_date_enregistrement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versement',
            name='avance',
        ),
        migrations.RemoveField(
            model_name='versement',
            name='reste_a_payer',
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='avance',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facturefournisseur',
            name='reste_a_payer',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='montant_versement',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
