# Generated by Django 4.1.6 on 2023-03-21 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0032_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='type_client',
        ),
        migrations.AddField(
            model_name='facture',
            name='avance',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_facturation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_facture',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='reste_a_payer',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
