# Generated by Django 4.1.6 on 2023-03-21 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stock', '0033_remove_facture_type_client_facture_avance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='save_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
