# Generated by Django 4.1.6 on 2023-03-21 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0034_facture_save_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='facture',
        ),
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.client'),
        ),
        migrations.AddField(
            model_name='vente',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
