# Generated by Django 4.1.6 on 2023-03-21 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0035_remove_vente_facture_vente_client_vente_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='reference_vente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.vente'),
        ),
    ]
