# Generated by Django 4.1.6 on 2023-03-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0036_facture_reference_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='reference_vente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
