# Generated by Django 4.1.6 on 2023-03-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0037_alter_facture_reference_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='monnaie',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
