# Generated by Django 4.1.6 on 2023-03-25 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0038_facture_monnaie'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersementClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_versement', models.FloatField(blank=True, max_length=200, null=True)),
                ('date_versement', models.DateField(blank=True, null=True)),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.facture')),
            ],
        ),
    ]
