# Generated by Django 4.1.6 on 2023-04-03 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stock', '0039_versementclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faccture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_vente', models.CharField(blank=True, max_length=200, null=True)),
                ('montant_facture', models.FloatField(blank=True, max_length=200, null=True)),
                ('avance', models.FloatField(blank=True, max_length=200, null=True)),
                ('reste_a_payer', models.FloatField(blank=True, max_length=200, null=True)),
                ('monnaie', models.FloatField(blank=True, max_length=200, null=True)),
                ('date_facturation', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('date_facture', models.DateField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.client')),
                ('save_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_remise', models.FloatField(blank=True, max_length=200, null=True)),
                ('ref_facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.faccture')),
            ],
        ),
        migrations.AlterField(
            model_name='versementclient',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Stock.faccture'),
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
