# Generated by Django 4.1.6 on 2023-04-03 13:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stock', '0040_faccture_remise_alter_versementclient_facture_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faccture',
            new_name='Facture',
        ),
    ]
