# Generated by Django 4.1.6 on 2023-04-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0042_delete_remise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeemballage',
            name='libelle',
            field=models.CharField(blank=True, choices=[('DETAIL', 'DETAIL'), ('CARTON', 'CARTON'), ('DEMI', 'DEMI'), ('QUART', 'QUART'), ('PACK', 'PACK')], max_length=200, null=True),
        ),
    ]
